### ISSUE TITLE
Error: Cannot find module 'easyxml'

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [gmetais/YellowLabTools#245]
PS C:\Users\jmallick> yellowlabtools www.google.co.in
module.js:471
    throw err;
    ^

Error: Cannot find module 'easyxml'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jmallick\AppData\Roaming\npm\node_modules\yellowlabtools\bin\cli.js:6:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by gmetais** [comment]
Can you see easyxml in YLT's node_modules directory?

It should be here: 
C:\Users\jmallick\AppData\Roaming\npm\node_modules\yellowlabtools\node_modules\easyxml\
